import { Registry } from 'prom-client';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { ConfigService } from '@nestjs/config';
export declare class MetricsService {
    private readonly eventEmitter;
    private readonly config;
    private readonly logger;
    private readonly registry;
    private readonly httpRequestsTotal;
    private readonly httpRequestDuration;
    private readonly httpRequestsInFlight;
    private readonly taskProcessingDuration;
    private readonly taskProcessingTotal;
    private readonly tasksInProgress;
    private readonly taskQueueSize;
    private readonly computerUseOperationsTotal;
    private readonly computerUseOperationDuration;
    private readonly computerUseErrors;
    private readonly aneProcessingDuration;
    private readonly websocketConnections;
    private readonly websocketMessages;
    private readonly websocketErrors;
    private readonly databaseConnections;
    private readonly databaseQueryDuration;
    private readonly databaseErrors;
    private readonly authenticationAttempts;
    private readonly authenticationDuration;
    private readonly activeUserSessions;
    private readonly authenticationFailures;
    private readonly sessionDuration;
    private readonly authorizationChecks;
    private readonly authorizationDuration;
    private readonly accessDenials;
    private readonly privilegeEscalations;
    private readonly rateLimitHits;
    private readonly rateLimitBypass;
    private readonly throttledRequests;
    private readonly rateLimitWindowUtilization;
    private readonly securityEvents;
    private readonly threatDetections;
    private readonly vulnerabilityScans;
    private readonly complianceChecks;
    private readonly tracingSpans;
    private readonly tracingErrors;
    private readonly logEvents;
    private readonly alertsTriggered;
    private readonly userInteractions;
    private readonly featureUsage;
    private readonly businessProcessDuration;
    private readonly revenueMetrics;
    private readonly memoryUsage;
    private readonly cpuUsage;
    private readonly diskUsage;
    private readonly applicationErrors;
    private readonly errorsByCategory;
    private readonly apiRequestsRate;
    private readonly taskSuccessRate;
    private readonly systemHealth;
    constructor(eventEmitter: EventEmitter2, config: ConfigService);
    getPrometheusMetrics(): Promise<string>;
    recordApiRequest(method: string, route: string, statusCode: number, duration: number, userId?: string): void;
    recordRequestStart(method: string, route: string): void;
    recordRequestEnd(method: string, route: string): void;
    recordTaskProcessing(taskType: string, status: 'completed' | 'failed' | 'cancelled', duration: number, userId?: string): void;
    setTasksInProgress(taskType: string, count: number, userId?: string): void;
    setTaskQueueSize(priority: string, size: number): void;
    recordComputerUseOperation(operationType: string, status: 'success' | 'error', duration: number, userId?: string): void;
    recordANEProcessing(operationType: string, status: 'success' | 'error', duration: number): void;
    recordComputerUseError(operationType: string, errorType: string): void;
    setWebSocketConnections(connectionType: string, count: number, userId?: string): void;
    recordWebSocketMessage(direction: 'incoming' | 'outgoing', messageType: string, userId?: string): void;
    recordWebSocketError(errorType: string, connectionType: string): void;
    setDatabaseConnections(database: string, state: string, count: number): void;
    recordDatabaseQuery(operation: string, table: string, duration: number, status?: 'success' | 'error'): void;
    recordDatabaseError(operation: string, errorType: string, table?: string): void;
    recordAuthAttempt(method: string, status: 'success' | 'failure', duration: number, userAgent?: string): void;
    setActiveUserSessions(sessionType: string, count: number): void;
    recordApplicationError(errorType: string, severity: 'low' | 'medium' | 'high' | 'critical', component: string): void;
    recordErrorByCategory(category: string, subcategory: string): void;
    updateBusinessMetrics(requestsPerSecond: number, taskSuccessRates: Record<string, number>): void;
    setSystemHealthScore(score: number): void;
    private startPeriodicCollection;
    private updateSystemMetrics;
    recordAuthFailure(method: string, reason: string, userAgent?: string): void;
    recordSessionDuration(sessionType: string, duration: number, terminationReason: string): void;
    recordAuthorizationCheck(resource: string, action: string, result: 'allowed' | 'denied', duration: number): void;
    recordAccessDenial(resource: string, reason: string, userRole: string): void;
    recordPrivilegeEscalation(userRole: string, targetRole: string, result: 'success' | 'failure'): void;
    recordRateLimitHit(endpoint: string, limitType: string, userId?: string): void;
    recordRateLimitBypass(endpoint: string, method: string, sourceIp: string): void;
    recordThrottledRequest(endpoint: string, throttleType: string): void;
    updateRateLimitUtilization(endpoint: string, windowDuration: string, utilizationPercent: number): void;
    recordSecurityEvent(eventType: string, severity: 'low' | 'medium' | 'high' | 'critical', source: string): void;
    recordThreatDetection(threatType: string, confidence: 'low' | 'medium' | 'high', mitigation: string): void;
    recordVulnerabilityScan(scanType: string, result: 'clean' | 'vulnerabilities_found', severity?: 'low' | 'medium' | 'high' | 'critical'): void;
    recordComplianceCheck(framework: string, control: string, result: 'compliant' | 'non_compliant'): void;
    recordTracingSpan(service: string, operation: string, status: 'success' | 'error'): void;
    recordTracingError(service: string, errorType: string): void;
    recordLogEvent(level: string, component: string, correlationId?: string): void;
    recordAlertTriggered(alertType: string, severity: 'low' | 'medium' | 'high' | 'critical', channel: string): void;
    recordUserInteraction(interactionType: string, feature: string, userSegment: string): void;
    recordFeatureUsage(feature: string, version: string, userType: string): void;
    recordBusinessProcess(processName: string, processVersion: string, result: 'success' | 'failure', duration: number): void;
    updateRevenueMetrics(metricType: string, value: number, currency: string, period: string): void;
    getMetricsSummary(): Promise<{
        security: any;
        performance: any;
        business: any;
        observability: any;
    }>;
    clearMetrics(): void;
    getRegistry(): Registry;
    recordHealthCheck(service: string, isHealthy: boolean, timestamp: number): void;
    recordDashboardAccess(operationId: string): void;
}
//# sourceMappingURL=metrics.service.d.ts.map