{{/*
Service Account for Bytebot Agent
Provides RBAC configuration and service identity
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bytebot-agent.serviceAccountName" . }}
  labels:
    {{- include "bytebot-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- end }}

---
{{/*
ClusterRole for Bytebot Agent
Defines cluster-wide permissions for monitoring and secrets access
*/}}
{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bytebot-agent.fullname" . }}-cluster-role
  labels:
    {{- include "bytebot-agent.labels" . | nindent 4 }}
rules:
# Read access to secrets for configuration
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# Read access to configmaps for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Read access to pods for health checks and monitoring
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Read access to services for service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Access to metrics endpoints for monitoring
- apiGroups: [""]
  resources: ["pods/metrics", "services/metrics"]
  verbs: ["get"]
# Access to node metrics for system monitoring
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "nodes/stats"]
  verbs: ["get", "list"]
{{- end }}

---
{{/*
Role for Bytebot Agent (Namespace-specific permissions)
Defines namespace-scoped permissions for application operation
*/}}
{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "bytebot-agent.fullname" . }}-role
  labels:
    {{- include "bytebot-agent.labels" . | nindent 4 }}
rules:
# Full access to secrets in the same namespace
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Full access to configmaps in the same namespace  
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Access to pods for health checks and lifecycle management
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Access to services for internal communication
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Access to persistent volume claims for data storage
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Access to events for monitoring and debugging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "patch"]
# Access to deployments for self-management
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
# Access to horizontal pod autoscalers
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
{{- end }}

---
{{/*
ClusterRoleBinding for Bytebot Agent
Binds cluster-wide permissions to the service account
*/}}
{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bytebot-agent.fullname" . }}-cluster-binding
  labels:
    {{- include "bytebot-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bytebot-agent.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "bytebot-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

---
{{/*
RoleBinding for Bytebot Agent
Binds namespace-scoped permissions to the service account
*/}}
{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bytebot-agent.fullname" . }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bytebot-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bytebot-agent.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "bytebot-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}